### ISSUE TITLE
CCL now supports package-local-nicknames

### ISSUE THREAD

**Issue by phoe** [rpav/defpackage-plus#4]
https://github.com/Clozure/ccl/pull/188

The current CCL master supports PLNs the same way that SBCL does. It also has `:PACKAGE-LOCAL-NICKNAMES` in its `*FEATURES*`.

`DEFPACKAGE-PLUS` should be updated to reflect this new development.

**Comment by djeis97** [comment]
I don't have a version of CCL to test it on, or the time right this second to set up one, but I just pushed what I think is the correct update for this to the ccl-pln-support branch of my fork. Once it has been tested I'll issue a full PR.

**Comment by phoe** [comment]
Fixed by https://github.com/rpav/defpackage-plus/pull/2
